// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityRow } from "./CapabilityRow";

/**
 * Per-agent effective capability set. `effective: None` => package not
 * installed; `Some([])` => agent sandboxed to nothing.
 */
export type AgentCapabilities = { agent_id: string, display_name: string, llm_backend: string, effective: Array<CapabilityRow> | null, };
