// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPrompt } from "./AgentPrompt";
import type { RequiredToolSpec } from "./RequiredToolSpec";

export type AgentDetail = { id: string, display_name: string | null, package: string | null, llm_backend: string | null, prompt: AgentPrompt, requires_tools: Array<RequiredToolSpec>, };
