// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentInfo = { id: string, llm_backend: string | null, package: string | null, source: string, };
