// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceKind } from "./SourceKind";
import type { SourceStatus } from "./SourceStatus";

export type BackendCredentialStatus = { backend: string, sources: Array<SourceStatus>, resolved: boolean, resolved_via: SourceKind | null, };
