// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Bundle = { path: string, sha256: string, size_bytes: bigint, built_at: string | null, };
