// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One capability row. Field names mirror tau's `tau list … --json` output and
 * the `tau.toml` schema: `allow_paths`/`deny_paths` for `fs.*`,
 * `allow_hosts`/`deny_hosts` for `net.http`, `allow_commands`/`deny_commands`
 * for `process.spawn`/`exec`, `max_bytes` for `fs.write`.
 */
export type CapabilityRow = { kind: string, allow_paths?: Array<string> | null, deny_paths: Array<string>, allow_hosts?: Array<string> | null, deny_hosts: Array<string>, allow_commands?: Array<string> | null, deny_commands: Array<string>, max_bytes?: bigint | null, };
