// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CategoryStatus } from "./CategoryStatus";
import type { CheckFinding } from "./CheckFinding";
import type { SandboxDiag } from "./SandboxDiag";

export type CheckReport = { categories: Array<CategoryStatus>, findings: Array<CheckFinding>, sandbox: SandboxDiag, };
