// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CheckFinding = { category: string, severity: string, rule: string, message: string, location: string | null, };
