// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IrAgent } from "./IrAgent";
import type { IrEdge } from "./IrEdge";
import type { IrTool } from "./IrTool";

/**
 * Flat, UI-facing projection of the compiled IR.
 */
export type CompiledIr = { hash_kind: string, canonical_ir_hash: string, target: string, tau_version: string, agents: Array<IrAgent>, tools: Array<IrTool>, edges: Array<IrEdge>, };
