// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../gateway/serde_json/JsonValue";

export type Event = { run_id: string, span_id: string | null, ts: string, 
/**
 * Free-form so unknown RunEvent kinds survive (RunEvent is #[non_exhaustive]).
 */
kind: string, payload: JsonValue, };
