// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IrAgent = { id: string, llm_backend: string, 
/**
 * Tool ids this agent wires to (derived from subflow edges).
 */
tools: Array<string>, };
