// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Package = { name: string, version: string, source: string, scope: string, version_count: number, };
