// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capability } from "./Capability";
import type { ToolSchema } from "./ToolSchema";

export type PluginDescribe = { port: string, protocol_version: number, tool: ToolSchema | null, capabilities: Array<Capability>, };
