// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A per-package introspection failure, surfaced as a UI error row.
 */
export type PluginError = { package: string, kind: string, message: string, };
