// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectSource = { "kind": "local" } | { "kind": "git", url: string, } | { "kind": "workspace" };
