// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentInfo } from "./AgentInfo";

export type ProjectConfig = { name: string, description: string | null, agents: Array<AgentInfo>, };
