// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Mode } from "./Mode";
import type { RunError } from "./RunError";
import type { RunStatus } from "./RunStatus";
import type { Source } from "./Source";
import type { Substrate } from "./Substrate";
import type { TokenUsage } from "./TokenUsage";

export type Run = { id: string, agent_id: string, prompt: string, substrate: Substrate, mode: Mode, status: RunStatus, started_at: string, ended_at: string | null, total_turns: number | null, token_usage: TokenUsage | null, stop_reason: string | null, error: RunError | null, source: Source, };
