// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionHeader } from "./SessionHeader";
import type { TurnSummary } from "./TurnSummary";

export type SessionDetail = { header: SessionHeader, 
/**
 * Opaque passthrough of each `tau_domain::Message` — never interpreted here.
 */
messages: Array<unknown>, turn_summaries: Array<TurnSummary>, };
