// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionPackage } from "./SessionPackage";

export type SessionHeader = { id: string, created_at: string, agent_id: string, llm_backend: string, package: SessionPackage, };
