// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SkillSummary = { name: string, version: string | null, source: string, editable: boolean, capability_kinds: Array<string>, requires_count: number, };
