// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capability } from "./Capability";
import type { PackageDep } from "./PackageDep";

export type SkillDetail = { name: string, description: string | null, version: string | null, source: string, editable: boolean, content: string, capabilities: Array<Capability>, requires_tools: Array<PackageDep>, requires_skills: Array<PackageDep>, };
