// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SourceKind = "env" | "local" | "vault" | "aws_kv" | "gcp_kv" | "azure_kv" | "token_broker" | "workload_identity";
