// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceKind } from "./SourceKind";

/**
 * Per-source status — NEVER carries a secret value.
 */
export type SourceStatus = { kind: SourceKind, ref: string | null, configured: boolean, gated: boolean, };
