// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Span kind. `Other` (`#[serde(other)]`) lets the gateway DESERIALIZE unknown
 * kinds at runtime without panicking (forward-compat). The generated TS union is
 * intentionally closed to the known kinds (`#[ts(skip)]` on `Other`); the frontend
 * branches on span `name`, not on an exhaustive `kind` switch, so this is safe.
 */
export type SpanKind = "run" | "turn" | "tool_call" | "agent" | "mcp_call" | "context_step";
