// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Target = { triple: string, platform: string, adapter_family: string, tier: string, status: string, required_shapes: Array<string>, };
