// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolDetail } from "./ToolDetail";

export type ToolCatalog = { tools: Array<ToolDetail>, 
/**
 * Count of plugins that failed to introspect; detail lives on the Plugins tab.
 */
error_count: number, };
