// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnSummary = { turn: number, stop_reason: string, input_tokens: bigint | null, output_tokens: bigint | null, };
