// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VerifyOutcome = { reproducible: boolean, shipped_sha256: string, rebuilt_sha256: string, diffs: Array<string>, };
