// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkflowNode = { id: string, kind: string, label: string, agent: string | null, tool: string | null, input: string | null, provider: string | null, tools: Array<string>, };
