// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Event } from "./Event";
import type { Run } from "./Run";
import type { Span } from "./Span";

/**
 * What the WS pushes to the browser: a tagged union of incremental updates.
 */
export type WsMessage = { "type": "snapshot", run: Run, spans: Array<Span>, } | { "type": "span_update", span: Span, } | { "type": "event", event: Event, } | { "type": "run_update", run: Run, };
